name: Maven Commons Lib Package

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:

      - name: Revision del codigo
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: 22
          distribution: 'adopt'
          cache: maven


      # Aquí configuramos Maven para que use las credenciales de GitHub
      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${{ secrets.USERNAME }}</username><password>${{ secrets.TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml

      # Incrementamos la versión usando una acción externa
      - name: Bump version and push tag
        id: bump_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.TOKEN }}
          default: patch

      # Build y deploy usando Maven sin necesidad de actualizar el pom.xml en el repositorio
      - name: Build and Deploy with Maven
        run: |
          mvn clean deploy -Pproduction
