name: Maven Commons Lib Package

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Revision del codigo
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: 22
          distribution: 'adopt'
          cache: maven

      - name: Incrementar version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$NF = $NF + 1 ; print}')
          mvn versions:set -DnewVersion=$NEW_VERSION
          echo "New version: $NEW_VERSION"

      - name: Build and Deploy with Maven
        run: |
          mvn clean deploy -Pproduction

      - name: Push updated version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add pom.xml
          git commit -m "Increment version to $NEW_VERSION"
          git push origin main